"""
Enterprise FizzBuzz Platform - Exception Hierarchy.

This package was split from a single module for parallel development.
All exception classes remain importable from this path.
"""

from enterprise_fizzbuzz.domain.exceptions._base import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.migrations import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.container import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.health import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.repository import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.metrics import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.webhooks import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.service_mesh import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.hot_reload import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.rate_limiter import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.compliance import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.finops import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.disaster_recovery import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.ab_testing import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.message_queue import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.secrets_vault import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.data_pipeline import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.openapi import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.blue_green import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.graph_db import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.genetic_algorithm import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.nlq import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.load_testing import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.audit_dashboard import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.gitops import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.formal_verification import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fbaas import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.time_travel import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.bytecode_vm import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.query_optimizer import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.paxos import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.cross_compiler import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.federated import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.knowledge_graph import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.self_modifying import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.compliance_chatbot import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.kernel import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.p2p_network import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzlang import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.recommendations import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.archaeology import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.dependent_types import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzkube import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzpm import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzsql import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.dap import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.ip_office import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.distributed_locks import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.cdc import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.billing import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.observability import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.capability_security import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.otel_tracing import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.intent_log import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.crdt import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.grammar import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.memory_allocator import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.columnar_storage import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.mapreduce import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.schema_evolution import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.model_check import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.sli import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.proxy import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.digital_logic import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.bloom import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.static_analysis import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.datalog import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.ssa_ir import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.proof_certificates import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.virtual_fs import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.audio_synth import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.network_stack import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.protein_folding import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizz_vcs import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.elf_format import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.replication import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.z_spec import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.flame_graph import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.regex_engine import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.spreadsheet import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.smart_contracts import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.dns_server import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.cpu_pipeline import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.spatial_db import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.clock_sync import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.bootloader import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.typesetting import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.video_codec import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.microkernel import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.cognitive_load import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.approval_workflow import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.pager import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.succession import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.performance_review import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.org_hierarchy import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.namespaces import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.cgroups import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.oci_runtime import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.overlay_fs import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.container_registry import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.cni import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.containerd import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzimage import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.container_chaos import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.container_ops import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.deploy import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.compose import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.kubev2 import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzlife import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzmvcc import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzlambda import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzwasm import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzs3 import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzstream import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzborrow import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzpolicy import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzadmit import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzlsp import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzsearch import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzsystemd import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzarrow import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizznvme import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzxdp import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzbtf import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzpaxosv2 import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzcuda import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzvirtio import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzebpfmap import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzavx import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizztpm import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizziommu import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzusb import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzpcie import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzefi import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzspdk import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzdpdk import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzsgx import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzhypervisor import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizznuma import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzrdma import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzinfiniband import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzcxl import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzsmartnic import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzfpga import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzquantumv2 import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzphotonic import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzneuromorphic import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzhomomorphic import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzzkp import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzdna import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzholographic import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzmemristor import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzoptane import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzreservoir import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzanneal import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzbrainwave import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzswarm import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzcellular import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzfractal import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizzchaostheory import *  # noqa: F401,F403
from enterprise_fizzbuzz.domain.exceptions.fizztopology import *  # noqa: F401,F403

# Explicit __all__ for IDE support and import * safety.
__all__ = [
    "FizzBuzzError",
    "ConfigurationError",
    "ConfigurationFileNotFoundError",
    "ConfigurationValidationError",
    "RuleEvaluationError",
    "RuleConflictError",
    "PluginLoadError",
    "PluginNotFoundError",
    "MiddlewareError",
    "FormatterError",
    "ObserverError",
    "ServiceNotInitializedError",
    "InvalidRangeError",
    "ModelConvergenceError",
    "BlockchainIntegrityError",
    "CircuitOpenError",
    "CircuitBreakerTimeoutError",
    "LocaleError",
    "LocaleNotFoundError",
    "TranslationKeyError",
    "FizzTranslationParseError",
    "PluralizationError",
    "LocaleChainExhaustedError",
    "AuthenticationError",
    "InsufficientFizzPrivilegesError",
    "NumberClassificationLevelExceededError",
    "TokenValidationError",
    "EventStoreError",
    "EventSequenceError",
    "EventDeserializationError",
    "SnapshotCorruptionError",
    "CommandValidationError",
    "CommandHandlerNotFoundError",
    "QueryHandlerNotFoundError",
    "ProjectionError",
    "TemporalQueryError",
    "EventVersionConflictError",
    "ChaosError",
    "ChaosInducedFizzBuzzError",
    "ChaosExperimentFailedError",
    "ChaosConfigurationError",
    "ResultCorruptionDetectedError",
    "FeatureFlagError",
    "FlagNotFoundError",
    "FlagDependencyCycleError",
    "FlagLifecycleError",
    "FlagDependencyNotMetError",
    "FlagRolloutError",
    "FlagTargetingError",
    "SLAError",
    "SLOViolationError",
    "ErrorBudgetExhaustedError",
    "AlertEscalationError",
    "OnCallNotFoundError",
    "SLAConfigurationError",
    "CacheError",
    "CacheCapacityExceededError",
    "CacheCoherenceViolationError",
    "CacheEntryExpiredError",
    "CacheWarmingError",
    "CachePolicyNotFoundError",
    "CacheInvalidationCascadeError",
    "MigrationError",
    "MigrationNotFoundError",
    "MigrationAlreadyAppliedError",
    "MigrationRollbackError",
    "MigrationDependencyError",
    "MigrationConflictError",
    "SchemaError",
    "SeedDataError",
    "CacheEulogyCompositionError",
    "DependencyInjectionError",
    "CircularDependencyError",
    "MissingBindingError",
    "DuplicateBindingError",
    "ScopeError",
    "HealthCheckError",
    "LivenessProbeFailedError",
    "ReadinessProbeFailedError",
    "StartupProbeFailedError",
    "SelfHealingFailedError",
    "HealthDashboardRenderError",
    "DownstreamFizzBuzzDegradationError",
    "RepositoryError",
    "ResultNotFoundError",
    "UnitOfWorkError",
    "RollbackError",
    "MetricsError",
    "MetricRegistrationError",
    "MetricNotFoundError",
    "CardinalityExplosionError",
    "InvalidMetricOperationError",
    "MetricsExportError",
    "WebhookError",
    "WebhookEndpointValidationError",
    "WebhookSignatureError",
    "WebhookDeliveryError",
    "WebhookRetryExhaustedError",
    "WebhookPayloadSerializationError",
    "WebhookDeadLetterQueueFullError",
    "ServiceMeshError",
    "ServiceNotFoundError",
    "MeshMTLSError",
    "SidecarProxyError",
    "MeshCircuitOpenError",
    "MeshLatencyInjectionError",
    "MeshPacketLossError",
    "CanaryDeploymentError",
    "LoadBalancerError",
    "MeshTopologyError",
    "HotReloadError",
    "ConfigDiffError",
    "ConfigValidationRejectedError",
    "RaftConsensusError",
    "SubsystemReloadError",
    "ConfigRollbackError",
    "ConfigWatcherError",
    "DependencyGraphCycleError",
    "HotReloadDashboardError",
    "RateLimitError",
    "RateLimitExceededError",
    "QuotaExhaustedError",
    "ComplianceError",
    "SOXSegregationViolationError",
    "GDPRErasureParadoxError",
    "GDPRConsentRequiredError",
    "HIPAAPrivacyViolationError",
    "HIPAAMinimumNecessaryError",
    "ComplianceFrameworkNotEnabledError",
    "ComplianceOfficerUnavailableError",
    "FinOpsError",
    "BudgetExceededError",
    "InvalidCostRateError",
    "CurrencyConversionError",
    "InvoiceGenerationError",
    "TaxCalculationError",
    "SavingsPlanError",
    "DisasterRecoveryError",
    "WALCorruptionError",
    "WALReplayError",
    "SnapshotCreationError",
    "SnapshotRestorationError",
    "BackupVaultFullError",
    "BackupNotFoundError",
    "PITRError",
    "RetentionPolicyError",
    "DRDrillError",
    "RPOViolationError",
    "RTOViolationError",
    "DRDashboardRenderError",
    "ABTestingError",
    "ExperimentNotFoundError",
    "ExperimentAlreadyExistsError",
    "ExperimentStateError",
    "InsufficientSampleSizeError",
    "MutualExclusionError",
    "TrafficAllocationError",
    "AutoRollbackTriggeredError",
    "StatisticalAnalysisError",
    "MessageQueueError",
    "TopicNotFoundError",
    "PartitionOutOfRangeError",
    "ConsumerGroupError",
    "OffsetOutOfRangeError",
    "SchemaValidationError",
    "DuplicateMessageError",
    "ProducerError",
    "ConsumerError",
    "RebalanceError",
    "BrokerError",
    "TopicAlreadyExistsError",
    "MessageSerializationError",
    "VaultError",
    "VaultSealedError",
    "VaultUnsealError",
    "VaultSecretNotFoundError",
    "VaultAccessDeniedError",
    "VaultEncryptionError",
    "VaultRotationError",
    "ShamirReconstructionError",
    "VaultSecretExpiredError",
    "VaultScanError",
    "VaultAlreadyInitializedError",
    "DataPipelineError",
    "SourceConnectorError",
    "SinkConnectorError",
    "ValidationStageError",
    "TransformStageError",
    "EnrichStageError",
    "LoadStageError",
    "DAGResolutionError",
    "CheckpointError",
    "BackfillError",
    "LineageTrackingError",
    "PipelineStageRetryExhaustedError",
    "OpenAPIError",
    "SchemaIntrospectionError",
    "EndpointRegistrationError",
    "ExceptionMappingError",
    "OpenAPISpecGenerationError",
    "SwaggerUIRenderError",
    "OpenAPIDashboardRenderError",
    "OpenAPISerializationError",
    "InvalidEndpointPathError",
    "DuplicateOperationIdError",
    "SecuritySchemeNotFoundError",
    "TagNotFoundError",
    "GatewayError",
    "RouteNotFoundError",
    "VersionNotSupportedError",
    "VersionDeprecatedError",
    "RequestTransformationError",
    "ResponseTransformationError",
    "APIKeyInvalidError",
    "APIKeyQuotaExceededError",
    "RequestReplayError",
    "GatewayDashboardRenderError",
    "DeploymentError",
    "SlotProvisioningError",
    "ShadowTrafficError",
    "SmokeTestFailureError",
    "BakePeriodError",
    "CutoverError",
    "DeploymentRollbackError",
    "DeploymentPhaseError",
    "PipelineDashboardRenderError",
    "GraphDatabaseError",
    "GraphNodeCreationError",
    "GraphEdgeCreationError",
    "CypherLiteError",
    "GraphPopulationError",
    "GraphAnalysisError",
    "GeneticAlgorithmError",
    "ChromosomeValidationError",
    "FitnessEvaluationError",
    "SelectionPressureError",
    "CrossoverIncompatibilityError",
    "MutationError",
    "ConvergenceTimeoutError",
    "PopulationExtinctionError",
    "GraphVisualizationError",
    "GraphMiddlewareError",
    "GraphDashboardRenderError",
    "NLQError",
    "NLQTokenizationError",
    "NLQIntentClassificationError",
    "NLQEntityExtractionError",
    "NLQExecutionError",
    "NLQUnsupportedQueryError",
    "LoadTestError",
    "LoadTestConfigurationError",
    "VirtualUserSpawnError",
    "LoadTestTimeoutError",
    "BottleneckAnalysisError",
    "PerformanceGradeError",
    "AuditDashboardError",
    "EventAggregationError",
    "AnomalyDetectionError",
    "TemporalCorrelationError",
    "EventStreamError",
    "DashboardRenderError",
    "GitOpsError",
    "GitOpsBranchNotFoundError",
    "GitOpsMergeConflictError",
    "GitOpsPolicyViolationError",
    "GitOpsProposalRejectedError",
    "GitOpsDriftDetectedError",
    "GitOpsCommitNotFoundError",
    "FormalVerificationError",
    "ProofObligationFailedError",
    "HoareTripleViolationError",
    "InductionBaseFailedError",
    "InductionStepFailedError",
    "PropertyVerificationTimeoutError",
    "FBaaSError",
    "TenantNotFoundError",
    "FBaaSQuotaExhaustedError",
    "TenantSuspendedError",
    "FeatureNotAvailableError",
    "BillingError",
    "InvalidAPIKeyError",
    "TimeTravelError",
    "TimelineEmptyError",
    "SnapshotIntegrityError",
    "BreakpointSyntaxError",
    "TimelineNavigationError",
    "BytecodeVMError",
    "BytecodeCompilationError",
    "BytecodeExecutionError",
    "BytecodeCycleLimitError",
    "BytecodeSerializationError",
    "QueryOptimizerError",
    "PlanGenerationError",
    "CostEstimationError",
    "PlanCacheOverflowError",
    "InvalidHintError",
    "PaxosError",
    "QuorumNotReachedError",
    "BallotRejectedError",
    "QuantumError",
    "QuantumDecoherenceError",
    "QuantumCircuitError",
    "QuantumMeasurementError",
    "QuantumAdvantageMirage",
    "ByzantineFaultDetectedError",
    "NetworkPartitionError",
    "ConsensusTimeoutError",
    "CrossCompilerError",
    "IRGenerationError",
    "CodeGenerationError",
    "RoundTripVerificationError",
    "UnsupportedTargetError",
    "FederatedLearningError",
    "FederatedClientTrainingError",
    "FederatedAggregationError",
    "FederatedPrivacyBudgetExhaustedError",
    "FederatedConvergenceError",
    "FederatedRoundTimeoutError",
    "KnowledgeGraphError",
    "InvalidTripleError",
    "NamespaceResolutionError",
    "FizzSPARQLSyntaxError",
    "InferenceFixpointError",
    "OntologyConsistencyError",
    "SelfModifyingCodeError",
    "ASTCorruptionError",
    "MutationSafetyViolation",
    "FitnessCollapseError",
    "MutationQuotaExhaustedError",
    "ComplianceChatbotError",
    "ChatbotIntentClassificationError",
    "ChatbotKnowledgeBaseError",
    "ChatbotSessionError",
    "KernelError",
    "KernelPanicError",
    "InvalidProcessStateError",
    "PageFaultError",
    "SchedulerStarvationError",
    "InterruptConflictError",
    "P2PNetworkError",
    "NodeUnreachableError",
    "GossipConvergenceError",
    "KademliaDHTError",
    "MerkleTreeDivergenceError",
    "P2PNetworkPartitionError",
    "DigitalTwinError",
    "TwinModelConstructionError",
    "TwinSimulationDivergenceError",
    "MonteCarloConvergenceError",
    "WhatIfScenarioParseError",
    "TwinDriftThresholdExceededError",
    "FizzLangError",
    "FizzLangLexerError",
    "FizzLangParseError",
    "FizzLangTypeError",
    "FizzLangRuntimeError",
    "RecommendationError",
    "ColdStartError",
    "SimilarityComputationError",
    "FilterBlendingError",
    "RecommendationExplanationError",
    "ArchaeologyError",
    "StratumCorruptionError",
    "InsufficientEvidenceError",
    "StratigraphicConflictError",
    "DependentTypeError",
    "WitnessConstructionError",
    "ProofObligationError",
    "TypeCheckError",
    "UnificationError",
    "FizzKubeError",
    "PodSchedulingError",
    "NodeNotReadyError",
    "ResourceQuotaExceededError",
    "EtcdKeyNotFoundError",
    "HPAScalingError",
    "PackageManagerError",
    "DependencyResolutionError",
    "PackageNotFoundError",
    "PackageIntegrityError",
    "PackageVersionConflictError",
    "FizzSQLError",
    "FizzSQLSyntaxError",
    "FizzSQLTableNotFoundError",
    "FizzSQLExecutionError",
    "DAPError",
    "DAPSessionError",
    "DAPBreakpointError",
    "DAPEvaluationError",
    "DAPProtocolError",
    "IPOfficeError",
    "TrademarkViolationError",
    "PatentInfringementError",
    "CopyrightInfringementError",
    "DistributedLockError",
    "LockAcquisitionTimeoutError",
    "LockDeadlockDetectedError",
    "LockTransactionAbortedError",
    "LockLeaseExpiredError",
    "CDCError",
    "CDCSchemaValidationError",
    "CDCOutboxRelayError",
    "CDCSinkError",
    "SubscriptionBillingError",
    "QuotaExceededError",
    "ContractValidationError",
    "RevenueRecognitionError",
    "DunningEscalationError",
    "ObservabilityCorrelationError",
    "CorrelationStrategyError",
    "CorrelationAnomalyDetectionError",
    "SignalIngestionError",
    "JITCompilationError",
    "JITTraceRecordingError",
    "JITOptimizationError",
    "JITGuardFailureError",
    "CapabilitySecurityError",
    "CapabilityVerificationError",
    "CapabilityAmplificationError",
    "CapabilityRevocationError",
    "OTelError",
    "OTelSpanError",
    "OTelExportError",
    "OTelSamplingError",
    "WriteAheadLogError",
    "IntentRollbackError",
    "CrashRecoveryError",
    "SavepointNotFoundError",
    "CRDTError",
    "CRDTMergeConflictError",
    "CRDTCausalityViolationError",
    "CRDTReplicaDivergenceError",
    "GrammarError",
    "GrammarSyntaxError",
    "GrammarConflictError",
    "GrammarParseError",
    "MemoryAllocatorError",
    "SlabExhaustedError",
    "ArenaOverflowError",
    "GarbageCollectionError",
    "ColumnarStorageError",
    "ColumnEncodingError",
    "RowGroupError",
    "ParquetExportError",
    "MapReduceError",
    "MapperError",
    "ReducerError",
    "ShuffleError",
    "SchemaEvolutionError",
    "SchemaCompatibilityError",
    "SchemaRegistrationError",
    "SchemaConsensusError",
    "ModelCheckError",
    "ModelCheckPropertyViolationError",
    "ModelCheckStateSpaceError",
    "ModelCheckInvalidSpecError",
    "SLIError",
    "SLIDefinitionError",
    "SLIBudgetExhaustionError",
    "SLIFeatureGateError",
    "ProxyError",
    "ProxyNoAvailableBackendsError",
    "ProxyBackendAlreadyExistsError",
    "ProxyHealthCheckError",
    "ProxyRoutingError",
    "CircuitSimulationError",
    "CircuitTopologyError",
    "CircuitSteadyStateError",
    "CircuitTimingViolationError",
    "ProbabilisticError",
    "BloomFilterCapacityError",
    "CountMinSketchOverflowError",
    "HyperLogLogPrecisionError",
    "LintError",
    "LintConfigurationError",
    "LintEngineError",
    "DatalogError",
    "DatalogStratificationError",
    "DatalogUnificationError",
    "DatalogQuerySyntaxError",
    "SSAIRError",
    "IRCompilationError",
    "SSAConstructionError",
    "IROptimizationError",
    "ProofCertificateError",
    "ProofTermError",
    "ProofCheckError",
    "CertificateExportError",
    "FileSystemError",
    "FileNotFoundError_",
    "PermissionDeniedError",
    "NotADirectoryError_",
    "IsADirectoryError_",
    "FileDescriptorError",
    "FileDescriptorLimitError",
    "MountError",
    "FileExistsError_",
    "ReadOnlyFileSystemError",
    "AudioSynthError",
    "InvalidWaveformError",
    "InvalidFrequencyError",
    "WAVWriteError",
    "EnvelopeConfigurationError",
    "FilterInstabilityError",
    "FizzNetError",
    "FizzNetChecksumError",
    "FizzNetConnectionRefusedError",
    "FizzNetConnectionResetError",
    "FizzNetTimeoutError",
    "FizzNetARPResolutionError",
    "FizzNetTTLExpiredError",
    "FizzNetProtocolError",
    "FizzFoldError",
    "FizzFoldSequenceError",
    "FizzFoldConvergenceError",
    "RayTracerError",
    "RayTracerSceneError",
    "RayTracerConvergenceError",
    "VCSError",
    "VCSObjectNotFoundError",
    "VCSMergeConflictError",
    "VCSBranchError",
    "VCSBisectError",
    "ELFFormatError",
    "ELFParseError",
    "ELFGenerationError",
    "ReplicationError",
    "ReplicationWALCorruptionError",
    "ReplicationFencingError",
    "ReplicationPromotionError",
    "ReplicationSplitBrainError",
    "ReplicationLagExceededError",
    "ZSpecError",
    "ZSpecTypeError",
    "ZSpecRefinementError",
    "FlameGraphError",
    "FlameGraphRenderError",
    "FlameGraphCollapseError",
    "FlameGraphDiffError",
    "TheoremProverError",
    "UnificationFailureError",
    "ResolutionExhaustionError",
    "CNFConversionError",
    "SkolemizationError",
    "RegexEngineError",
    "RegexPatternSyntaxError",
    "RegexCompilationError",
    "SpreadsheetError",
    "SpreadsheetCellReferenceError",
    "SpreadsheetFormulaParseError",
    "SpreadsheetCircularReferenceError",
    "SpreadsheetFunctionError",
    "SpreadsheetRangeError",
    "SmartContractError",
    "SmartContractCompilationError",
    "SmartContractDeploymentError",
    "SmartContractExecutionError",
    "SmartContractOutOfGasError",
    "SmartContractStackOverflowError",
    "SmartContractStackUnderflowError",
    "SmartContractInvalidJumpError",
    "SmartContractRevertError",
    "SmartContractStorageError",
    "SmartContractGovernanceError",
    "DNSError",
    "DNSZoneLoadError",
    "DNSWireFormatError",
    "DNSQueryResolutionError",
    "DNSNegativeCacheError",
    "DNSZoneTransferError",
    "ShaderError",
    "ShaderCompilationError",
    "ShaderExecutionError",
    "WarpDivergenceError",
    "GPUMemoryError",
    "CPUPipelineError",
    "PipelineHazardError",
    "PipelineStallError",
    "BranchMispredictionError",
    "PipelineFlushError",
    "SpatialError",
    "SpatialIndexError",
    "SpatialQueryParseError",
    "CoordinateMappingError",
    "SpatialPredicateError",
    "ClockSyncError",
    "ClockDriftExceededError",
    "StratumError",
    "NTPPacketError",
    "BootloaderError",
    "BootPostError",
    "BootSectorError",
    "TypesettingError",
    "LineBreakingError",
    "PaginationError",
    "PostScriptRenderError",
    "CodecError",
    "CodecBitstreamError",
    "CodecFrameError",
    "CodecQuantizationError",
    "IPCError",
    "IPCPortNotFoundError",
    "IPCTaskNotFoundError",
    "IPCPermissionError",
    "IPCDeadlockError",
    "IPCQueueFullError",
    "IPCTimeoutError",
    "IPCRightTransferError",
    "BobError",
    "BobCalibrationError",
    "BobCircadianError",
    "BobAlertFatigueError",
    "BobBurnoutError",
    "BobOverloadError",
    "BobDashboardError",
    "BobMiddlewareError",
    "BobTLXError",
    "ApprovalError",
    "ApprovalPolicyError",
    "ApprovalQuorumError",
    "ApprovalConflictOfInterestError",
    "ApprovalDelegationError",
    "ApprovalTimeoutError",
    "ApprovalAuditError",
    "ApprovalMiddlewareError",
    "PagerError",
    "PagerAlertError",
    "PagerDeduplicationError",
    "PagerCorrelationError",
    "PagerEscalationError",
    "PagerIncidentError",
    "PagerScheduleError",
    "PagerDashboardError",
    "PagerMiddlewareError",
    "SuccessionError",
    "SuccessionBusFactorError",
    "SuccessionSkillsMatrixError",
    "SuccessionPCRSError",
    "SuccessionKnowledgeGapError",
    "SuccessionHiringPlanError",
    "SuccessionKnowledgeTransferError",
    "SuccessionReportError",
    "SuccessionMiddlewareError",
    "PerfError",
    "PerfGoalError",
    "PerfSelfAssessmentError",
    "PerfFeedbackError",
    "PerfCalibrationError",
    "PerfCompensationError",
    "PerfReviewCycleError",
    "PerfReportError",
    "PerfDashboardError",
    "PerfMiddlewareError",
    "OrgError",
    "OrgDepartmentError",
    "OrgPositionError",
    "OrgHierarchyError",
    "OrgRACIError",
    "OrgHeadcountError",
    "OrgCommitteeError",
    "OrgChartError",
    "OrgDashboardError",
    "OrgMiddlewareError",
    "NamespaceError",
    "NamespaceCreationError",
    "NamespaceDestroyError",
    "NamespaceEntryError",
    "NamespaceLeaveError",
    "NamespaceRefCountError",
    "NamespaceHierarchyError",
    "NamespaceTypeError",
    "PIDNamespaceError",
    "NETNamespaceError",
    "MNTNamespaceError",
    "UTSNamespaceError",
    "IPCNamespaceError",
    "USERNamespaceError",
    "CGROUPNamespaceError",
    "NamespaceManagerError",
    "NamespaceDashboardError",
    "NamespaceMiddlewareError",
    "CgroupError",
    "CgroupCreationError",
    "CgroupRemovalError",
    "CgroupAttachError",
    "CgroupMigrationError",
    "CgroupHierarchyError",
    "CgroupDelegationError",
    "CgroupControllerError",
    "CPUControllerError",
    "MemoryControllerError",
    "IOControllerError",
    "PIDsControllerError",
    "OOMKillerError",
    "ResourceAccountantError",
    "CgroupQuotaExceededError",
    "CgroupThrottleError",
    "CgroupManagerError",
    "CgroupDashboardError",
    "CgroupMiddlewareError",
    "OCIRuntimeError",
    "OCIConfigError",
    "OCIConfigSchemaError",
    "OCIBundleError",
    "OCIContainerError",
    "OCIStateTransitionError",
    "OCIContainerNotFoundError",
    "OCIContainerExistsError",
    "OCICreateError",
    "OCIStartError",
    "OCIKillError",
    "OCIDeleteError",
    "SeccompError",
    "SeccompRuleError",
    "HookError",
    "HookTimeoutError",
    "RlimitError",
    "MountError",
    "OCIRuntimeMiddlewareError",
    "OCIDashboardError",
    "OverlayError",
    "LayerNotFoundError",
    "LayerExistsError",
    "LayerCorruptionError",
    "LayerDigestMismatchError",
    "OverlayMountError",
    "OverlayMountStateError",
    "CopyOnWriteError",
    "WhiteoutError",
    "SnapshotError",
    "SnapshotNotFoundError",
    "SnapshotStateError",
    "DiffError",
    "LayerCacheError",
    "TarArchiveError",
    "TarCompressionError",
    "OverlayDashboardError",
    "OverlayMiddlewareError",
    "LayerStoreFullError",
    "OverlayProviderError",
    "RegistryError",
    "BlobNotFoundError",
    "BlobCorruptionError",
    "BlobStoreFullError",
    "ManifestNotFoundError",
    "ManifestValidationError",
    "ManifestExistsError",
    "RepositoryNotFoundError",
    "RepositoryLimitError",
    "TagNotFoundError",
    "TagLimitError",
    "FizzFileParseError",
    "FizzFileMissingFromError",
    "ImageBuildError",
    "LayerCacheMissError",
    "GarbageCollectionError",
    "ImageSignatureError",
    "VulnerabilityScanError",
    "RegistryDashboardError",
    "RegistryMiddlewareError",
    "CNIError",
    "CNIPluginNotFoundError",
    "CNIAddError",
    "CNIDeleteError",
    "CNICheckError",
    "VethCreationError",
    "BridgeError",
    "IPAMError",
    "IPAMExhaustedError",
    "IPAMLeaseExpiredError",
    "IPAMConflictError",
    "PortMappingError",
    "PortConflictError",
    "ContainerDNSError",
    "NetworkPolicyError",
    "OverlayNetworkError",
    "CNIDashboardError",
    "CNIMiddlewareError",
    "ContainerdError",
    "ContainerdDaemonError",
    "ContainerCreateError",
    "ContainerNotFoundError",
    "ContainerAlreadyExistsError",
    "TaskCreateError",
    "TaskNotFoundError",
    "TaskAlreadyRunningError",
    "TaskExecError",
    "ShimError",
    "ShimNotFoundError",
    "ShimConnectionError",
    "ContentStoreError",
    "ContentNotFoundError",
    "MetadataStoreError",
    "ImagePullError",
    "ImageNotFoundError",
    "GarbageCollectorError",
    "CRIError",
    "ContainerdMiddlewareError",
    "FizzImageError",
    "CatalogInitializationError",
    "ImageNotFoundInCatalogError",
    "ImageAlreadyExistsInCatalogError",
    "ImageBuildError",
    "ImageBuildDependencyError",
    "FizzFileGenerationError",
    "ImageDependencyRuleViolationError",
    "ImageLayerCreationError",
    "ImageDigestMismatchError",
    "ImageVulnerabilityScanError",
    "ImageBlockedByScanError",
    "ImageVersionConflictError",
    "MultiArchBuildError",
    "PlatformResolutionError",
    "InitContainerImageBuildError",
    "SidecarImageBuildError",
    "CatalogCapacityError",
    "ImageCircularDependencyError",
    "ImageMetadataValidationError",
    "FizzImageMiddlewareError",
    "ContainerChaosError",
    "ChaosExperimentNotFoundError",
    "ChaosExperimentAlreadyRunningError",
    "ChaosExperimentAbortedError",
    "ChaosExperimentFailedStartError",
    "ChaosFaultInjectionError",
    "ChaosFaultRemovalError",
    "ChaosContainerKillError",
    "ChaosNetworkPartitionError",
    "ChaosCPUStressError",
    "ChaosMemoryPressureError",
    "ChaosDiskFillError",
    "ChaosImagePullFailureError",
    "ChaosDNSFailureError",
    "ChaosNetworkLatencyError",
    "ChaosGameDayError",
    "ChaosGameDayAbortError",
    "ChaosBlastRadiusExceededError",
    "ChaosSteadyStateViolationError",
    "ChaosCognitiveLoadGateError",
    "ChaosScheduleError",
    "ChaosReportGenerationError",
    "ChaosTargetResolutionError",
    "ChaosContainerChaosMiddlewareError",
    "ContainerOpsError",
    "ContainerOpsLogCollectorError",
    "ContainerOpsLogIndexError",
    "ContainerOpsLogQueryError",
    "ContainerOpsLogRetentionError",
    "ContainerOpsMetricsCollectorError",
    "ContainerOpsMetricsStoreError",
    "ContainerOpsMetricsAlertError",
    "ContainerOpsTraceExtenderError",
    "ContainerOpsTraceDashboardError",
    "ContainerOpsExecError",
    "ContainerOpsExecTimeoutError",
    "ContainerOpsOverlayDiffError",
    "ContainerOpsProcessTreeError",
    "ContainerOpsFlameGraphError",
    "ContainerOpsDashboardError",
    "ContainerOpsDashboardRenderError",
    "ContainerOpsCorrelationError",
    "ContainerOpsQuerySyntaxError",
    "ContainerOpsMiddlewareError",
    "DeployError",
    "DeployPipelineError",
    "DeployStageError",
    "DeployStepError",
    "DeployStrategyError",
    "RollingUpdateError",
    "BlueGreenError",
    "CanaryError",
    "RecreateError",
    "DeployManifestError",
    "ManifestParseError",
    "ManifestValidationError",
    "GitOpsReconcileError",
    "GitOpsDriftError",
    "GitOpsSyncError",
    "RollbackError",
    "RollbackRevisionNotFoundError",
    "RollbackStrategyError",
    "DeployGateError",
    "CognitiveLoadGateError",
    "DeployDashboardError",
    "DeployMiddlewareError",
    "ComposeError",
    "ComposeFileNotFoundError",
    "ComposeFileParseError",
    "ComposeVariableInterpolationError",
    "ComposeCircularDependencyError",
    "ComposeServiceNotFoundError",
    "ComposeServiceStartError",
    "ComposeServiceStopError",
    "ComposeHealthCheckTimeoutError",
    "ComposeNetworkCreateError",
    "ComposeNetworkNotFoundError",
    "ComposeVolumeCreateError",
    "ComposeVolumeNotFoundError",
    "ComposeScaleError",
    "ComposeExecError",
    "ComposeRestartError",
    "ComposeRestartPolicyExhaustedError",
    "ComposePortConflictError",
    "ComposeImageNotFoundError",
    "ComposeProjectAlreadyRunningError",
    "ComposeMiddlewareError",
    "KubeV2Error",
    "KubeletV2Error",
    "KV2ImagePullError",
    "ImagePullBackOffError",
    "ImageNotPresentError",
    "PullSecretError",
    "InitContainerFailedError",
    "InitContainerTimeoutError",
    "SidecarInjectionError",
    "SidecarLifecycleError",
    "ProbeFailedError",
    "ProbeTimeoutError",
    "ReadinessProbeFailedError",
    "LivenessProbeFailedError",
    "StartupProbeFailedError",
    "VolumeProvisionError",
    "VolumeMountError",
    "PVCNotFoundError",
    "ContainerRestartBackoffError",
    "PodTerminationError",
    "KubeV2MiddlewareError",
    "FizzLifeError",
    "FizzLifeGridInitializationError",
    "FizzLifeKernelConfigurationError",
    "FizzLifeGrowthFunctionError",
    "FizzLifeConvergenceError",
    "FizzLifeMassConservationViolation",
    "FizzLifeSpeciesClassificationError",
    "FizzLifeFFTError",
    "LocalizationError",
    "TranslationFileParseError",
    "TranslationKeyMissingError",
    "PluralizationRuleError",
    "MVCCError",
    "TransactionError",
    "InvalidTransactionStateError",
    "TransactionNotFoundError",
    "LongRunningTransactionError",
    "TransactionReadOnlyError",
    "ConflictError",
    "WriteConflictError",
    "SerializationFailureError",
    "OptimisticValidationError",
    "DeadlockError",
    "LockError",
    "LockTimeoutError",
    "LockEscalationError",
    "ConnectionPoolError",
    "ConnectionPoolExhaustedError",
    "ConnectionValidationError",
    "SnapshotError",
    "SnapshotTooOldError",
    "PreparedStatementError",
    "PlanInvalidatedError",
    "ParameterTypeMismatchError",
    "MVCCMiddlewareError",
    "FizzLambdaError",
    "FunctionNotFoundError",
    "FunctionAlreadyExistsError",
    "FunctionRegistryError",
    "FunctionVersionError",
    "FunctionVersionNotFoundError",
    "AliasNotFoundError",
    "AliasAlreadyExistsError",
    "InvocationError",
    "InvocationTimeoutError",
    "InvocationThrottledError",
    "InvocationPayloadError",
    "ExecutionEnvironmentError",
    "ColdStartError",
    "WarmPoolError",
    "WarmPoolCapacityError",
    "ColdStartOptimizerError",
    "SnapshotCaptureError",
    "SnapshotRestoreError",
    "TriggerError",
    "TriggerNotFoundError",
    "HTTPTriggerError",
    "TimerTriggerError",
    "QueueTriggerError",
    "EventBusTriggerError",
    "DeadLetterQueueError",
    "QueueFullError",
    "QueueMessageNotFoundError",
    "RetryExhaustedError",
    "LayerError",
    "LayerNotFoundError",
    "LayerLimitExceededError",
    "ResourceAllocationError",
    "FunctionPackagingError",
    "AutoScalerError",
    "TrafficShiftError",
    "ConcurrencyLimitError",
    "FizzLambdaMiddlewareError",
    "FizzLambdaCognitiveLoadError",
    "FizzLambdaComplianceError",
    "StreamProcessingError",
    "StreamJobSubmissionError",
    "StreamJobNotFoundError",
    "StreamSourceError",
    "StreamSinkError",
    "StreamOperatorError",
    "StreamCheckpointError",
    "StreamCheckpointRestoreError",
    "StreamSavepointError",
    "StreamSavepointRestoreError",
    "WatermarkViolationError",
    "WindowError",
    "StateAccessError",
    "StateBackendError",
    "KeyGroupAssignmentError",
    "StreamJoinError",
    "CEPPatternError",
    "CEPMatchError",
    "BackpressureError",
    "ScaleError",
    "StreamSQLError",
    "RestartExhaustedError",
    "BarrierAlignmentTimeoutError",
    "StreamMiddlewareError",
    "StateTTLError",
    # fizzpolicy
    "PolicyEngineError",
    "PolicyLexerError",
    "PolicyParserError",
    "PolicyTypeCheckError",
    "PolicyPartialEvalError",
    "PolicyPlanGeneratorError",
    "PolicyEvaluationError",
    "PolicyEvaluationTimeoutError",
    "PolicyEvaluationLimitError",
    "PolicyBundleError",
    "PolicyBundleBuildError",
    "PolicyBundleIntegrityError",
    "PolicyBundleVersionError",
    "PolicyBundleStoreError",
    "PolicyBundleSigningError",
    "PolicyDecisionLogError",
    "PolicyDecisionQueryError",
    "PolicyDecisionExportError",
    "PolicyDataAdapterError",
    "PolicyDataRefreshError",
    "PolicyTestError",
    "PolicyTestFailedError",
    "PolicyCoverageError",
    "PolicyBenchmarkError",
    "PolicyWatcherError",
    "PolicyHotReloadError",
    "PolicyBuiltinError",
    "PolicyAdmissionDeniedError",
    "PolicyMiddlewareError",
    "FizzAdmitError",
    "AdmissionChainError",
    "AdmissionControllerError",
    "AdmissionDeniedError",
    "AdmissionTimeoutError",
    "AdmissionWebhookError",
    "AdmissionWebhookUnreachableError",
    "ResourceQuotaExhaustedError",
    "LimitRangeViolationError",
    "PodSecurityViolationError",
    "ImagePolicyViolationError",
    "CRDError",
    "CRDSchemaValidationError",
    "CRDRegistrationError",
    "CRDInstanceValidationError",
    "CRDNotFoundError",
    "CRDDeletionError",
    "OperatorError",
    "OperatorReconcileError",
    "OperatorLeaderElectionError",
    "OperatorWorkQueueError",
    "FinalizerError",
    "FinalizerStuckError",
    "FinalizerRemovalError",
    "OwnerReferenceError",
    "GarbageCollectionError",
    "CascadingDeletionError",
    "FizzAdmitMiddlewareError",
    "FizzLSPError",
    "FizzLSPTransportError",
    "FizzLSPProtocolError",
    "FizzLSPSessionError",
    "FizzLSPDocumentError",
    "FizzLSPDocumentSyncError",
    "FizzLSPAnalysisError",
    "FizzLSPCompletionError",
    "FizzLSPDiagnosticError",
    "FizzLSPDefinitionError",
    "FizzLSPHoverError",
    "FizzLSPReferencesError",
    "FizzLSPRenameError",
    "FizzLSPRenameConflictError",
    "FizzLSPSemanticTokenError",
    "FizzLSPCodeActionError",
    "FizzLSPFormattingError",
    "FizzLSPSymbolError",
    "FizzLSPDispatchError",
    "FizzLSPMiddlewareError",
    # FizzSearch
    "FizzSearchError",
    "FizzSearchIndexNotFoundError",
    "FizzSearchIndexAlreadyExistsError",
    "FizzSearchDocumentNotFoundError",
    "FizzSearchMappingError",
    "FizzSearchAnalyzerError",
    "FizzSearchQueryParseError",
    "FizzSearchQueryExecutionError",
    "FizzSearchScrollExpiredError",
    "FizzSearchScrollLimitError",
    "FizzSearchMergePolicyError",
    "FizzSearchSegmentError",
    "FizzSearchHighlightError",
    "FizzSearchAggregationError",
    "FizzSearchSortError",
    "FizzSearchBulkError",
    "FizzSearchReindexError",
    "FizzSearchAliasError",
    "FizzSearchCapacityError",
    "FizzSearchConcurrencyError",
    "FizzSearchFacetError",
    "FizzSearchScoringError",
    "FizzSearchTokenizerError",
    "FizzSearchIndexerError",
    "FizzSearchMiddlewareError",
    # FizzSystemd
    "SystemdError",
    "UnitFileParseError",
    "UnitNotFoundError",
    "UnitMaskedError",
    "DependencyCycleError",
    "DependencyConflictError",
    "TransactionError",
    "ServiceStartError",
    "ServiceStopError",
    "ServiceTimeoutError",
    "WatchdogTimeoutError",
    "RestartLimitHitError",
    "SocketActivationError",
    "SocketBindError",
    "TimerParseError",
    "MountError",
    "JournalError",
    "JournalSealVerificationError",
    "CgroupDelegationError",
    "InhibitorLockError",
    "ShutdownInhibitedError",
    "BusError",
    "TransientUnitError",
    "BootFailureError",
    "SystemdMiddlewareError",
    # FizzArrow
    "FizzArrowError",
    "FizzArrowSchemaError",
    "FizzArrowBatchError",
    "FizzArrowBatchNotFoundError",
    "FizzArrowColumnNotFoundError",
    "FizzArrowTypeMismatchError",
    "FizzArrowAggregationError",
    "FizzArrowFilterError",
    "FizzArrowNullBitmapError",
    "FizzArrowEmptyBatchError",
    "FizzArrowRowCountMismatchError",
    "FizzArrowUnsupportedOperationError",
    "FizzArrowMiddlewareError",
    "FizzArrowDashboardError",
    "FizzArrowDuplicateColumnError",
    # FizzNVMe
    "FizzNVMeError",
    "FizzNVMeNamespaceError",
    "FizzNVMeNamespaceNotFoundError",
    "FizzNVMeQueueError",
    "FizzNVMeQueueNotFoundError",
    "FizzNVMeQueueFullError",
    "FizzNVMeCommandError",
    "FizzNVMeInvalidLBAError",
    "FizzNVMeDataSizeMismatchError",
    "FizzNVMeControllerError",
    "FizzNVMeReadUnwrittenError",
    "FizzNVMeDuplicateNamespaceError",
    "FizzNVMeDuplicateQueueError",
    "FizzNVMeMiddlewareError",
    "FizzNVMeDashboardError",
    # FizzCUDA
    "CUDAError",
    "CUDADeviceNotFoundError",
    "CUDAKernelLaunchError",
    "CUDAMemoryError",
    "CUDAStreamError",
    "CUDAInvalidBlockDimError",
    "CUDASharedMemoryExceededError",
    "CUDASynchronizationError",
    # FizzVirtIO
    "VirtIOError",
    "VirtIODeviceNotFoundError",
    "VirtIOQueueFullError",
    "VirtIODescriptorChainError",
    "VirtIORingError",
    "VirtIODeviceStatusError",
    "VirtIOFeatureNegotiationError",
    "VirtIOBusError",
    # FizzEBPFMap
    "EBPFMapError",
    "EBPFMapNotFoundError",
    "EBPFMapFullError",
    "EBPFMapKeyError",
    "EBPFMapKeySizeError",
    "EBPFMapValueSizeError",
    "EBPFRingBufferError",
    "EBPFLPMTrieError",
    # FizzAVX
    "AVXError",
    "AVXRegisterError",
    "AVXLaneError",
    "AVXWidthMismatchError",
    "AVXMaskError",
    "AVXShuffleError",
    "AVXAlignmentError",
    "AVXUnsupportedOperationError",
    # FizzTPM
    "TPMError",
    "TPMPCRError",
    "TPMSealError",
    "TPMUnsealError",
    "TPMAttestationError",
    "TPMNVRAMError",
    "TPMAuthorizationError",
    "TPMRandomError",
    # FizzIOMMU
    "IOMMUError",
    "IOMMUPageFaultError",
    "IOMMUDeviceNotFoundError",
    "IOMMUPermissionError",
    "IOMMUMappingError",
    "IOMMUInterruptRemapError",
    "IOMMUPageTableError",
    "IOMMUIsolationViolationError",
    # FizzUSB
    "USBError",
    "USBEnumerationError",
    "USBTransferError",
    "USBDescriptorError",
    "USBEndpointError",
    "USBBandwidthError",
    "USBStallError",
    "USBTimeoutError",
    # FizzPCIe
    "PCIeError",
    "PCIeConfigSpaceError",
    "PCIeBARError",
    "PCIeInterruptError",
    "PCIeLinkTrainingError",
    "PCIeTLPError",
    "PCIeCompletionTimeoutError",
    "PCIeDeviceNotFoundError",
    # FizzEFI
    "EFIError",
    "EFIBootServiceError",
    "EFIRuntimeServiceError",
    "EFIVariableError",
    "EFIDriverLoadError",
    "EFISecureBootError",
    "EFIBootManagerError",
    "EFIProtocolError",
    # FizzSPDK
    "SPDKError",
    "SPDKBdevError",
    "SPDKIOChannelError",
    "SPDKNVMeError",
    "SPDKDMAError",
    "SPDKPollerError",
    "SPDKTargetError",
    "SPDKIOPSBudgetError",
    # FizzDPDK
    "DPDKError",
    "DPDKPortError",
    "DPDKMbufPoolError",
    "DPDKRingError",
    "DPDKFlowError",
    "DPDKRSSError",
    "DPDKTxError",
    "DPDKRxError",
    # FizzSGX
    "SGXError",
    "SGXEnclaveCreationError",
    "SGXECallError",
    "SGXOCallError",
    "SGXSealError",
    "SGXAttestationError",
    "SGXMemoryError",
    "SGXMeasurementError",
    # FizzHypervisor
    "HypervisorError",
    "VMCreationError",
    "VCPUSchedulingError",
    "EPTViolationError",
    "VMCSError",
    "VMExitError",
    "MemoryVirtualizationError",
    "VMLifecycleError",
    # FizzNUMA
    "NUMAError",
    "NUMANodeError",
    "NUMADistanceError",
    "NUMAPlacementError",
    "NUMAAffinityError",
    "NUMAMigrationError",
    "NUMATopologyError",
    # FizzRDMA
    "RDMAError",
    "RDMAMemoryRegionError",
    "RDMAProtectionDomainError",
    "RDMAQueuePairError",
    "RDMACompletionError",
    "RDMASendError",
    "RDMAReadError",
    "RDMAWriteError",
    # FizzInfiniBand
    "InfiniBandError",
    "IBSubnetManagerError",
    "IBLIDAssignmentError",
    "IBPathRoutingError",
    "IBServiceLevelError",
    "IBPartitionKeyError",
    "IBMulticastError",
    "IBGIDError",
    # FizzCXL
    "CXLError",
    "CXLDeviceError",
    "CXLMemoryPoolError",
    "CXLCoherencyError",
    "CXLHDMDecoderError",
    "CXLBackInvalidationError",
    "CXLFlitError",
    "CXLBISnpError",
    # FizzSmartNIC
    "SmartNICError",
    "SmartNICProgramError",
    "SmartNICFlowTableError",
    "SmartNICAccelerationError",
    "SmartNICClassificationError",
    "SmartNICChecksumError",
    "SmartNICQueueError",
    "SmartNICFirmwareError",
    # FizzDNA
    "FizzDNAError",
    "DNAEncodingError",
    "DNADecodingError",
    "GCContentImbalanceError",
    "ECCChecksumError",
    "HomopolymerRunError",
    "DNAStorageCapacityError",
    "DNAMiddlewareError",
    # FizzHolographic
    "FizzHolographicError",
    "HologramWriteError",
    "HologramReadError",
    "AngularMultiplexingError",
    "ReferenceBeamError",
    "DiffractionEfficiencyError",
    "CrystalSaturationError",
    "HolographicMiddlewareError",
    # FizzMemristor
    "FizzMemristorError",
    "CrossbarDimensionError",
    "ResistanceStateError",
    "SneakPathError",
    "DeviceEnduranceError",
    "AnalogPrecisionError",
    "MemristorMiddlewareError",
    # FizzOptane
    "FizzOptaneError",
    "DAXMappingError",
    "PersistenceBarrierError",
    "CrashConsistencyError",
    "PMEMAllocatorError",
    "TransactionAbortError",
    "OptaneMiddlewareError",
    # FizzReservoir
    "FizzReservoirError",
    "SpectralRadiusError",
    "ReservoirDimensionError",
    "ReadoutTrainingError",
    "EchoStateViolationError",
    "InputScalingError",
    "ReservoirMiddlewareError",
    # FizzAnneal
    "FizzAnnealError",
    "QUBOFormulationError",
    "IsingModelError",
    "AnnealingScheduleError",
    "SolutionSamplingError",
    "EnergyLandscapeError",
    "AnnealMiddlewareError",
    # FizzBrainwave
    "FizzBrainwaveError",
    "EEGSignalError",
    "ArtifactRejectionError",
    "SpectralDecompositionError",
    "MentalStateClassificationError",
    "NeuralDecodingError",
    "BrainwaveMiddlewareError",
    # FizzSwarm
    "FizzSwarmError",
    "PheromoneEvaporationError",
    "ParticleVelocityDivergenceError",
    "SwarmConvergenceError",
    "StigmergyError",
    "ForagerAllocationError",
    "SwarmMiddlewareError",
    # FizzCellular
    "FizzCellularError",
    "InvalidRuleNumberError",
    "GridDimensionError",
    "StateEvolutionError",
    "PatternDetectionError",
    "BoundaryConditionError",
    "CellularMiddlewareError",
    # FizzFractal
    "FizzFractalError",
    "MandelbrotDivergenceError",
    "JuliaSetError",
    "LSystemGrammarError",
    "FractalDimensionError",
    "IterationDepthError",
    "FractalMiddlewareError",
    # FizzChaos
    "FizzChaosTheoryError",
    "LorenzAttractorError",
    "LogisticMapError",
    "LyapunovExponentError",
    "BifurcationError",
    "StrangeAttractorError",
    "ChaosTheoryMiddlewareError",
    # FizzTopology
    "FizzTopologyError",
    "SimplicialComplexError",
    "FiltrationError",
    "BettiNumberError",
    "PersistenceDiagramError",
    "VietorisRipsError",
    "TopologyMiddlewareError",
]
