"""
Enterprise FizzBuzz Platform - FizzMaterialScience: Materials Simulator

Implements crystal lattice simulation, stress-strain curve computation,
phase diagram construction, thermal conductivity estimation, Young's
modulus calculation, and alloy composition analysis for FizzBuzz
evaluation numbers.

The connection between FizzBuzz and materials science is direct: every
integer maps to a point in a composition-temperature phase space. Numbers
divisible by 3 occupy the FCC (face-centered cubic) region; numbers
divisible by 5 occupy the BCC (body-centered cubic) region; numbers
divisible by 15 sit on the FCC-BCC phase boundary. Understanding the
mechanical and thermal properties at each point is essential for
predicting the structural integrity of the FizzBuzz output under
operational loads.

The stress-strain analysis determines whether the output string can
withstand the mechanical loads imposed by rendering to the terminal.
Young's modulus quantifies the stiffness of the classification, and
thermal conductivity governs how quickly a FizzBuzz result dissipates
the heat generated by its own computational overhead. These are not
optional analyses — they are the physical foundation upon which the
entire platform rests.
"""

from __future__ import annotations

import logging
import math
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Callable, Dict, List, Optional, Tuple

from enterprise_fizzbuzz.domain.interfaces import IMiddleware
from enterprise_fizzbuzz.domain.models import ProcessingContext

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

# Boltzmann constant (eV/K)
BOLTZMANN_EV = 8.617333262e-5

# Universal gas constant (J/(mol*K))
GAS_CONSTANT = 8.314462618

# Room temperature (K)
ROOM_TEMPERATURE_K = 293.15

# Debye temperature defaults for common lattice types (K)
DEBYE_TEMPERATURE_FCC = 345.0  # Copper-like
DEBYE_TEMPERATURE_BCC = 470.0  # Iron-like
DEBYE_TEMPERATURE_HCP = 400.0  # Titanium-like

# Yield stress defaults (MPa)
DEFAULT_YIELD_STRESS = 250.0

# Strain rate for quasi-static loading (1/s)
DEFAULT_STRAIN_RATE = 1.0e-3


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class CrystalStructure(Enum):
    """Bravais lattice types relevant to FizzBuzz metallurgy."""
    FCC = auto()  # Face-centered cubic — Fizz numbers
    BCC = auto()  # Body-centered cubic — Buzz numbers
    HCP = auto()  # Hexagonal close-packed — FizzBuzz numbers
    SIMPLE_CUBIC = auto()  # Simple cubic — Plain numbers
    DIAMOND = auto()  # Diamond cubic — Prime numbers


class PhaseType(Enum):
    """Thermodynamic phase classifications."""
    ALPHA = auto()
    BETA = auto()
    GAMMA = auto()
    LIQUID = auto()
    AMORPHOUS = auto()


class DeformationMode(Enum):
    """Mechanical deformation modes."""
    ELASTIC = auto()
    PLASTIC = auto()
    FRACTURE = auto()


# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------


@dataclass
class LatticeParameters:
    """Crystal lattice parameters.

    Defines the unit cell of a Bravais lattice in terms of lattice
    constants (a, b, c) and angles (alpha, beta, gamma).
    """
    structure: CrystalStructure = CrystalStructure.FCC
    a: float = 3.615  # Angstroms (Cu default)
    b: float = 3.615
    c: float = 3.615
    alpha_deg: float = 90.0
    beta_deg: float = 90.0
    gamma_deg: float = 90.0
    atoms_per_cell: int = 4  # FCC default

    @property
    def volume(self) -> float:
        """Unit cell volume in cubic Angstroms."""
        alpha = math.radians(self.alpha_deg)
        beta = math.radians(self.beta_deg)
        gamma = math.radians(self.gamma_deg)
        cos_a = math.cos(alpha)
        cos_b = math.cos(beta)
        cos_g = math.cos(gamma)
        factor = math.sqrt(
            1.0 - cos_a ** 2 - cos_b ** 2 - cos_g ** 2
            + 2.0 * cos_a * cos_b * cos_g
        )
        return self.a * self.b * self.c * factor

    @property
    def packing_fraction(self) -> float:
        """Atomic packing fraction for the lattice type."""
        packing = {
            CrystalStructure.FCC: math.pi / (3.0 * math.sqrt(2.0)),
            CrystalStructure.BCC: math.pi * math.sqrt(3.0) / 8.0,
            CrystalStructure.HCP: math.pi / (3.0 * math.sqrt(2.0)),
            CrystalStructure.SIMPLE_CUBIC: math.pi / 6.0,
            CrystalStructure.DIAMOND: math.pi * math.sqrt(3.0) / 16.0,
        }
        return packing.get(self.structure, math.pi / 6.0)


@dataclass
class StressStrainPoint:
    """A single point on the stress-strain curve."""
    strain: float = 0.0
    stress_mpa: float = 0.0
    mode: DeformationMode = DeformationMode.ELASTIC


@dataclass
class StressStrainCurve:
    """Complete stress-strain curve for a material."""
    points: list[StressStrainPoint] = field(default_factory=list)
    youngs_modulus_gpa: float = 0.0
    yield_stress_mpa: float = 0.0
    ultimate_stress_mpa: float = 0.0
    fracture_strain: float = 0.0

    @property
    def is_valid(self) -> bool:
        return (
            self.youngs_modulus_gpa > 0
            and self.yield_stress_mpa > 0
            and len(self.points) > 0
        )


@dataclass
class PhaseDiagramPoint:
    """A point in a binary phase diagram."""
    temperature_k: float = 0.0
    composition: float = 0.0  # Mole fraction of component B [0, 1]
    phase: PhaseType = PhaseType.ALPHA
    gibbs_energy_j: float = 0.0


@dataclass
class AlloyComposition:
    """Composition of a multi-component alloy."""
    components: dict[str, float] = field(default_factory=dict)

    @property
    def is_valid(self) -> bool:
        if not self.components:
            return False
        total = sum(self.components.values())
        return (
            abs(total - 1.0) < 1e-6
            and all(0.0 <= v <= 1.0 for v in self.components.values())
        )


@dataclass
class MaterialProperties:
    """Collected material properties from a full analysis."""
    lattice: LatticeParameters = field(default_factory=LatticeParameters)
    stress_strain: StressStrainCurve = field(default_factory=StressStrainCurve)
    thermal_conductivity_w_mk: float = 0.0
    youngs_modulus_gpa: float = 0.0
    phase: PhaseType = PhaseType.ALPHA
    alloy: AlloyComposition = field(default_factory=AlloyComposition)
    debye_temperature_k: float = 0.0


# ---------------------------------------------------------------------------
# Crystal Lattice Engine
# ---------------------------------------------------------------------------


class CrystalLatticeEngine:
    """Constructs and analyzes crystal lattice structures.

    Maps FizzBuzz classification to crystal structures: Fizz numbers
    crystallize as FCC, Buzz numbers as BCC, FizzBuzz as HCP, plain
    numbers as simple cubic, and primes as diamond cubic. The lattice
    constant scales with the number magnitude.
    """

    def build_lattice(self, number: int, is_fizz: bool, is_buzz: bool) -> LatticeParameters:
        """Construct a crystal lattice for the given FizzBuzz classification."""
        structure = self._classify_structure(number, is_fizz, is_buzz)
        a = self._compute_lattice_constant(number, structure)

        atoms = {
            CrystalStructure.FCC: 4,
            CrystalStructure.BCC: 2,
            CrystalStructure.HCP: 6,
            CrystalStructure.SIMPLE_CUBIC: 1,
            CrystalStructure.DIAMOND: 8,
        }

        lattice = LatticeParameters(
            structure=structure,
            a=a,
            b=a,
            c=a if structure != CrystalStructure.HCP else a * 1.633,
            alpha_deg=90.0,
            beta_deg=90.0,
            gamma_deg=90.0 if structure != CrystalStructure.HCP else 120.0,
            atoms_per_cell=atoms.get(structure, 1),
        )

        if lattice.volume <= 0:
            from enterprise_fizzbuzz.domain.exceptions.fizzmaterialscience import (
                LatticeConstructionError,
            )
            raise LatticeConstructionError(
                structure.name, "unit cell volume is non-positive"
            )

        return lattice

    def _classify_structure(
        self, number: int, is_fizz: bool, is_buzz: bool
    ) -> CrystalStructure:
        if is_fizz and is_buzz:
            return CrystalStructure.HCP
        elif is_fizz:
            return CrystalStructure.FCC
        elif is_buzz:
            return CrystalStructure.BCC
        elif self._is_prime(number):
            return CrystalStructure.DIAMOND
        else:
            return CrystalStructure.SIMPLE_CUBIC

    def _compute_lattice_constant(
        self, number: int, structure: CrystalStructure
    ) -> float:
        """Compute lattice constant in Angstroms, scaled by number magnitude."""
        base = {
            CrystalStructure.FCC: 3.615,
            CrystalStructure.BCC: 2.870,
            CrystalStructure.HCP: 3.209,
            CrystalStructure.SIMPLE_CUBIC: 2.650,
            CrystalStructure.DIAMOND: 5.431,
        }
        a0 = base.get(structure, 3.0)
        scale = 1.0 + 0.001 * (number % 100)
        return a0 * scale

    @staticmethod
    def _is_prime(n: int) -> bool:
        if n < 2:
            return False
        if n < 4:
            return True
        if n % 2 == 0 or n % 3 == 0:
            return False
        i = 5
        while i * i <= n:
            if n % i == 0 or n % (i + 2) == 0:
                return False
            i += 6
        return True

    def nearest_neighbor_distance(self, lattice: LatticeParameters) -> float:
        """Compute nearest-neighbor distance in Angstroms."""
        if lattice.structure == CrystalStructure.FCC:
            return lattice.a / math.sqrt(2.0)
        elif lattice.structure == CrystalStructure.BCC:
            return lattice.a * math.sqrt(3.0) / 2.0
        elif lattice.structure == CrystalStructure.HCP:
            return lattice.a
        elif lattice.structure == CrystalStructure.DIAMOND:
            return lattice.a * math.sqrt(3.0) / 4.0
        else:
            return lattice.a

    def coordination_number(self, structure: CrystalStructure) -> int:
        """Return the coordination number for the given structure."""
        cn = {
            CrystalStructure.FCC: 12,
            CrystalStructure.BCC: 8,
            CrystalStructure.HCP: 12,
            CrystalStructure.SIMPLE_CUBIC: 6,
            CrystalStructure.DIAMOND: 4,
        }
        return cn.get(structure, 6)


# ---------------------------------------------------------------------------
# Stress-Strain Engine
# ---------------------------------------------------------------------------


class StressStrainEngine:
    """Computes stress-strain curves for FizzBuzz materials.

    Uses a combined elastic-plastic constitutive model with linear
    hardening. The elastic region follows Hooke's law (sigma = E * epsilon),
    the plastic region follows the Ramberg-Osgood relation, and fracture
    occurs at the ultimate tensile strength.
    """

    def compute_curve(
        self,
        youngs_modulus_gpa: float,
        yield_stress_mpa: float,
        hardening_exponent: float = 0.15,
        num_points: int = 50,
    ) -> StressStrainCurve:
        """Generate a stress-strain curve."""
        if youngs_modulus_gpa <= 0:
            from enterprise_fizzbuzz.domain.exceptions.fizzmaterialscience import (
                YoungModulusError,
            )
            raise YoungModulusError("computed_material", youngs_modulus_gpa)

        e_mpa = youngs_modulus_gpa * 1000.0
        yield_strain = yield_stress_mpa / e_mpa
        uts_mpa = yield_stress_mpa * (1.0 + hardening_exponent * 10.0)
        fracture_strain = yield_strain * 20.0

        points: list[StressStrainPoint] = []

        for i in range(num_points):
            strain = fracture_strain * i / (num_points - 1)

            if strain <= yield_strain:
                stress = e_mpa * strain
                mode = DeformationMode.ELASTIC
            elif strain <= fracture_strain * 0.9:
                plastic_strain = strain - yield_strain
                stress = yield_stress_mpa + (
                    uts_mpa - yield_stress_mpa
                ) * (1.0 - math.exp(-10.0 * plastic_strain / fracture_strain))
                mode = DeformationMode.PLASTIC
            else:
                frac_progress = (strain - fracture_strain * 0.9) / (
                    fracture_strain * 0.1
                )
                stress = uts_mpa * (1.0 - frac_progress * 0.3)
                mode = DeformationMode.FRACTURE

            if stress < 0:
                from enterprise_fizzbuzz.domain.exceptions.fizzmaterialscience import (
                    StressStrainError,
                )
                raise StressStrainError(
                    stress, strain, "negative stress in tensile loading"
                )

            points.append(StressStrainPoint(strain=strain, stress_mpa=stress, mode=mode))

        return StressStrainCurve(
            points=points,
            youngs_modulus_gpa=youngs_modulus_gpa,
            yield_stress_mpa=yield_stress_mpa,
            ultimate_stress_mpa=uts_mpa,
            fracture_strain=fracture_strain,
        )


# ---------------------------------------------------------------------------
# Phase Diagram Engine
# ---------------------------------------------------------------------------


class PhaseDiagramEngine:
    """Constructs binary phase diagrams for FizzBuzz alloy systems.

    The Fizz-Buzz binary system has a simple eutectic phase diagram:
    the alpha phase (Fizz-rich) and beta phase (Buzz-rich) are separated
    by a two-phase region, with a eutectic point at the composition
    corresponding to FizzBuzz (x = 3/15 = 0.2).
    """

    def __init__(
        self,
        melting_a_k: float = 1358.0,  # Copper-like
        melting_b_k: float = 1811.0,  # Iron-like
        eutectic_temp_k: float = 1100.0,
        eutectic_comp: float = 0.2,
    ) -> None:
        self._melting_a = melting_a_k
        self._melting_b = melting_b_k
        self._eutectic_temp = eutectic_temp_k
        self._eutectic_comp = eutectic_comp

    def compute_phase(
        self, temperature_k: float, composition: float
    ) -> PhaseDiagramPoint:
        """Determine the thermodynamic phase at a given T-x point."""
        if composition < 0.0 or composition > 1.0:
            from enterprise_fizzbuzz.domain.exceptions.fizzmaterialscience import (
                PhaseDiagramError,
            )
            raise PhaseDiagramError(
                temperature_k, composition, "composition must be in [0, 1]"
            )

        if temperature_k < 0:
            from enterprise_fizzbuzz.domain.exceptions.fizzmaterialscience import (
                PhaseDiagramError,
            )
            raise PhaseDiagramError(
                temperature_k, composition, "temperature must be non-negative"
            )

        liquidus_t = self._liquidus_temperature(composition)
        gibbs = self._gibbs_energy(temperature_k, composition)

        if temperature_k > liquidus_t:
            phase = PhaseType.LIQUID
        elif composition < self._eutectic_comp:
            phase = PhaseType.ALPHA
        elif composition > 1.0 - self._eutectic_comp:
            phase = PhaseType.BETA
        else:
            if temperature_k > self._eutectic_temp:
                phase = PhaseType.GAMMA
            else:
                phase = PhaseType.ALPHA

        return PhaseDiagramPoint(
            temperature_k=temperature_k,
            composition=composition,
            phase=phase,
            gibbs_energy_j=gibbs,
        )

    def _liquidus_temperature(self, composition: float) -> float:
        """Compute the liquidus temperature at a given composition."""
        t_a = self._melting_a
        t_b = self._melting_b
        t_e = self._eutectic_temp
        x_e = self._eutectic_comp

        if composition <= x_e:
            frac = composition / x_e if x_e > 0 else 0.0
            return t_a - (t_a - t_e) * frac
        else:
            frac = (composition - x_e) / (1.0 - x_e)
            return t_e + (t_b - t_e) * frac

    def _gibbs_energy(self, temperature_k: float, composition: float) -> float:
        """Compute Gibbs free energy of mixing (simplified regular solution)."""
        if composition <= 0 or composition >= 1.0:
            return 0.0
        omega = 20000.0  # Interaction parameter (J/mol)
        x = composition
        mixing_entropy = GAS_CONSTANT * temperature_k * (
            x * math.log(x) + (1.0 - x) * math.log(1.0 - x)
        )
        mixing_enthalpy = omega * x * (1.0 - x)
        return mixing_enthalpy + mixing_entropy

    def compute_phase_boundaries(
        self, num_points: int = 50
    ) -> list[PhaseDiagramPoint]:
        """Compute the liquidus line across the full composition range."""
        points: list[PhaseDiagramPoint] = []
        for i in range(num_points):
            x = i / (num_points - 1)
            t = self._liquidus_temperature(x)
            pt = self.compute_phase(t - 1.0, x)
            points.append(
                PhaseDiagramPoint(
                    temperature_k=t,
                    composition=x,
                    phase=PhaseType.LIQUID,
                    gibbs_energy_j=pt.gibbs_energy_j,
                )
            )
        return points


# ---------------------------------------------------------------------------
# Thermal Conductivity Engine
# ---------------------------------------------------------------------------


class ThermalConductivityEngine:
    """Estimates thermal conductivity using the Debye model.

    Thermal conductivity is computed from the phonon contribution using
    k = (1/3) * C_v * v_s * l, where C_v is the volumetric heat capacity,
    v_s is the speed of sound, and l is the phonon mean free path.
    """

    def compute(
        self,
        debye_temp_k: float,
        temperature_k: float = ROOM_TEMPERATURE_K,
        lattice_param_a: float = 3.615,
    ) -> float:
        """Estimate thermal conductivity in W/(m*K)."""
        if temperature_k <= 0:
            from enterprise_fizzbuzz.domain.exceptions.fizzmaterialscience import (
                ThermalConductivityError,
            )
            raise ThermalConductivityError("computed_material", 0.0)

        # Volumetric heat capacity (Dulong-Petit limit approximation)
        x = debye_temp_k / temperature_k
        if x < 0.1:
            cv = 3.0 * GAS_CONSTANT
        else:
            cv = 3.0 * GAS_CONSTANT * self._debye_cv_ratio(x)

        # Speed of sound (m/s) — estimated from Debye temperature
        v_s = debye_temp_k * BOLTZMANN_EV * 1.602e-19 / (
            1.055e-34 * (6.0 * math.pi ** 2 / (lattice_param_a * 1e-10) ** 3) ** (1.0 / 3.0)
        )
        v_s = abs(v_s)

        # Mean free path (simplified — inversely proportional to T at high T)
        mfp = lattice_param_a * 1e-10 * 100.0 * (debye_temp_k / temperature_k)

        # k = (1/3) * C_v * v_s * mfp, convert to W/(m*K)
        molar_volume = (lattice_param_a * 1e-10) ** 3 * 6.022e23
        cv_volumetric = cv / molar_volume if molar_volume > 0 else cv

        conductivity = (1.0 / 3.0) * cv_volumetric * v_s * mfp

        if conductivity < 0:
            from enterprise_fizzbuzz.domain.exceptions.fizzmaterialscience import (
                ThermalConductivityError,
            )
            raise ThermalConductivityError("computed_material", conductivity)

        return conductivity

    @staticmethod
    def _debye_cv_ratio(x: float) -> float:
        """Approximate Debye heat capacity ratio C_v / 3NkB."""
        if x <= 0:
            return 1.0
        if x > 20:
            return (4.0 * math.pi ** 4) / (5.0 * x ** 3)
        # Numerical integration (trapezoidal) of Debye function
        n_steps = 100
        dt = x / n_steps
        integral = 0.0
        for i in range(1, n_steps + 1):
            t = i * dt
            if t > 500:
                break
            exp_t = math.exp(t)
            integrand = t ** 4 * exp_t / (exp_t - 1.0) ** 2
            integral += integrand * dt
        return (3.0 / x ** 3) * integral


# ---------------------------------------------------------------------------
# Young's Modulus Calculator
# ---------------------------------------------------------------------------


class YoungModulusCalculator:
    """Calculates Young's modulus from lattice parameters.

    Uses the empirical Blackman relation between elastic constants and
    lattice geometry. For cubic crystals, E = C11 - 2*C12^2 / (C11 + C12),
    where C11 and C12 are estimated from the cohesive energy and lattice
    constant.
    """

    # Approximate elastic constants (GPa) by crystal structure
    _C11_TABLE: dict[CrystalStructure, float] = {
        CrystalStructure.FCC: 168.0,
        CrystalStructure.BCC: 231.0,
        CrystalStructure.HCP: 162.0,
        CrystalStructure.SIMPLE_CUBIC: 100.0,
        CrystalStructure.DIAMOND: 165.0,
    }

    _C12_TABLE: dict[CrystalStructure, float] = {
        CrystalStructure.FCC: 121.0,
        CrystalStructure.BCC: 135.0,
        CrystalStructure.HCP: 92.0,
        CrystalStructure.SIMPLE_CUBIC: 50.0,
        CrystalStructure.DIAMOND: 64.0,
    }

    def compute(self, lattice: LatticeParameters) -> float:
        """Compute Young's modulus in GPa."""
        c11 = self._C11_TABLE.get(lattice.structure, 100.0)
        c12 = self._C12_TABLE.get(lattice.structure, 50.0)

        # Scale by lattice constant ratio
        a0 = {
            CrystalStructure.FCC: 3.615,
            CrystalStructure.BCC: 2.870,
            CrystalStructure.HCP: 3.209,
            CrystalStructure.SIMPLE_CUBIC: 2.650,
            CrystalStructure.DIAMOND: 5.431,
        }.get(lattice.structure, 3.0)

        scale = (a0 / lattice.a) ** 3 if lattice.a > 0 else 1.0
        c11 *= scale
        c12 *= scale

        # Voigt-Reuss-Hill average for polycrystalline Young's modulus
        denom = c11 + c12
        if abs(denom) < 1e-12:
            from enterprise_fizzbuzz.domain.exceptions.fizzmaterialscience import (
                YoungModulusError,
            )
            raise YoungModulusError("computed_material", 0.0)

        e_vrh = (c11 - c12) * (c11 + 2.0 * c12) / (c11 + c12)

        if e_vrh <= 0:
            from enterprise_fizzbuzz.domain.exceptions.fizzmaterialscience import (
                YoungModulusError,
            )
            raise YoungModulusError("computed_material", e_vrh)

        return e_vrh


# ---------------------------------------------------------------------------
# Alloy Composition Analyzer
# ---------------------------------------------------------------------------


class AlloyCompositionAnalyzer:
    """Analyzes alloy compositions derived from FizzBuzz classifications.

    The composition is derived from the number's divisibility profile:
    - Fizz component (Fz): fraction based on divisibility by 3
    - Buzz component (Bz): fraction based on divisibility by 5
    - Neutral component (N): remainder

    This ternary alloy system (Fz-Bz-N) has rich phase behavior that
    directly impacts the mechanical properties of the FizzBuzz output.
    """

    def compute_composition(
        self, number: int, is_fizz: bool, is_buzz: bool
    ) -> AlloyComposition:
        """Compute alloy composition from FizzBuzz classification."""
        fizz_frac = 0.0
        buzz_frac = 0.0

        if is_fizz and is_buzz:
            fizz_frac = 0.4
            buzz_frac = 0.4
        elif is_fizz:
            fizz_frac = 0.6
            buzz_frac = 0.1
        elif is_buzz:
            fizz_frac = 0.1
            buzz_frac = 0.6
        else:
            digit_sum = sum(int(d) for d in str(abs(number))) if number != 0 else 0
            fizz_frac = (digit_sum % 10) / 50.0
            buzz_frac = ((digit_sum * 7) % 10) / 50.0

        neutral_frac = 1.0 - fizz_frac - buzz_frac
        neutral_frac = max(0.0, neutral_frac)

        total = fizz_frac + buzz_frac + neutral_frac
        if total > 0:
            fizz_frac /= total
            buzz_frac /= total
            neutral_frac /= total

        comp = AlloyComposition(
            components={"Fz": fizz_frac, "Bz": buzz_frac, "N": neutral_frac}
        )

        if not comp.is_valid:
            from enterprise_fizzbuzz.domain.exceptions.fizzmaterialscience import (
                AlloyCompositionError,
            )
            raise AlloyCompositionError(
                comp.components, "component fractions do not sum to 1.0"
            )

        return comp


# ---------------------------------------------------------------------------
# Material Science Engine
# ---------------------------------------------------------------------------


class MaterialScienceEngine:
    """Integrates all material science analysis components.

    Performs a complete material characterization for each FizzBuzz
    evaluation: crystal structure determination, mechanical property
    calculation, thermal analysis, and alloy composition profiling.
    """

    def __init__(self) -> None:
        self.lattice_engine = CrystalLatticeEngine()
        self.stress_strain_engine = StressStrainEngine()
        self.phase_diagram_engine = PhaseDiagramEngine()
        self.thermal_engine = ThermalConductivityEngine()
        self.youngs_engine = YoungModulusCalculator()
        self.alloy_analyzer = AlloyCompositionAnalyzer()
        self._analysis_count = 0

    def analyze_number(
        self, number: int, is_fizz: bool, is_buzz: bool
    ) -> MaterialProperties:
        """Perform full material characterization for a FizzBuzz number."""
        self._analysis_count += 1

        lattice = self.lattice_engine.build_lattice(number, is_fizz, is_buzz)

        youngs_modulus = self.youngs_engine.compute(lattice)

        yield_stress = DEFAULT_YIELD_STRESS * (1.0 + 0.01 * (number % 50))
        stress_strain = self.stress_strain_engine.compute_curve(
            youngs_modulus_gpa=youngs_modulus,
            yield_stress_mpa=yield_stress,
        )

        debye_t = {
            CrystalStructure.FCC: DEBYE_TEMPERATURE_FCC,
            CrystalStructure.BCC: DEBYE_TEMPERATURE_BCC,
            CrystalStructure.HCP: DEBYE_TEMPERATURE_HCP,
        }.get(lattice.structure, 350.0)

        thermal_k = self.thermal_engine.compute(
            debye_temp_k=debye_t,
            lattice_param_a=lattice.a,
        )

        composition_frac = (number % 100) / 100.0
        phase_pt = self.phase_diagram_engine.compute_phase(
            ROOM_TEMPERATURE_K, composition_frac
        )

        alloy = self.alloy_analyzer.compute_composition(number, is_fizz, is_buzz)

        return MaterialProperties(
            lattice=lattice,
            stress_strain=stress_strain,
            thermal_conductivity_w_mk=thermal_k,
            youngs_modulus_gpa=youngs_modulus,
            phase=phase_pt.phase,
            alloy=alloy,
            debye_temperature_k=debye_t,
        )

    @property
    def analysis_count(self) -> int:
        return self._analysis_count


# ---------------------------------------------------------------------------
# Middleware
# ---------------------------------------------------------------------------


class MaterialScienceMiddleware(IMiddleware):
    """Middleware that performs material science analysis for each evaluation.

    Each number is characterized as a crystalline material with specific
    lattice structure, mechanical properties, and thermal behavior. The
    results are attached to the processing context metadata for
    consumption by downstream middleware.

    Priority 292 positions this in the physical sciences tier.
    """

    def __init__(self) -> None:
        self._engine = MaterialScienceEngine()
        self._evaluations = 0

    def get_name(self) -> str:
        return "fizzmaterialscience"

    def get_priority(self) -> int:
        return 292

    @property
    def engine(self) -> MaterialScienceEngine:
        return self._engine

    def process(
        self,
        context: ProcessingContext,
        next_handler: Callable[[ProcessingContext], ProcessingContext],
    ) -> ProcessingContext:
        result = next_handler(context)

        number = context.number
        is_fizz = False
        is_buzz = False
        if result.results:
            latest = result.results[-1]
            is_fizz = latest.is_fizz
            is_buzz = latest.is_buzz

        try:
            props = self._engine.analyze_number(number, is_fizz, is_buzz)
            self._evaluations += 1

            result.metadata["material_science"] = {
                "crystal_structure": props.lattice.structure.name,
                "lattice_constant_a": round(props.lattice.a, 4),
                "packing_fraction": round(props.lattice.packing_fraction, 4),
                "youngs_modulus_gpa": round(props.youngs_modulus_gpa, 2),
                "thermal_conductivity_w_mk": round(props.thermal_conductivity_w_mk, 4),
                "phase": props.phase.name,
                "yield_stress_mpa": round(props.stress_strain.yield_stress_mpa, 2),
                "alloy_composition": {
                    k: round(v, 4) for k, v in props.alloy.components.items()
                },
                "debye_temperature_k": props.debye_temperature_k,
            }

            logger.debug(
                "FizzMaterialScience: number=%d structure=%s E=%.2f GPa",
                number,
                props.lattice.structure.name,
                props.youngs_modulus_gpa,
            )

        except Exception:
            logger.exception(
                "FizzMaterialScience: analysis failed for number %d", number
            )

        return result
