"""Core pipeline events."""

from enterprise_fizzbuzz.domain.events._registry import EventType

EventType.register("SESSION_STARTED")
EventType.register("SESSION_ENDED")
EventType.register("NUMBER_PROCESSING_STARTED")
EventType.register("NUMBER_PROCESSED")
EventType.register("RULE_MATCHED")
EventType.register("RULE_NOT_MATCHED")
EventType.register("FIZZ_DETECTED")
EventType.register("BUZZ_DETECTED")
EventType.register("FIZZBUZZ_DETECTED")
EventType.register("PLAIN_NUMBER_DETECTED")
EventType.register("MIDDLEWARE_ENTERED")
EventType.register("MIDDLEWARE_EXITED")
EventType.register("OUTPUT_FORMATTED")
EventType.register("ERROR_OCCURRED")
EventType.register("CIRCUIT_BREAKER_STATE_CHANGED")
EventType.register("CIRCUIT_BREAKER_TRIPPED")
EventType.register("CIRCUIT_BREAKER_RECOVERED")
EventType.register("CIRCUIT_BREAKER_HALF_OPEN")
EventType.register("CIRCUIT_BREAKER_CALL_REJECTED")
EventType.register("TRACE_STARTED")
EventType.register("TRACE_ENDED")
EventType.register("SPAN_STARTED")
EventType.register("SPAN_ENDED")
EventType.register("AUTHORIZATION_GRANTED")
EventType.register("AUTHORIZATION_DENIED")
EventType.register("TOKEN_VALIDATED")
EventType.register("TOKEN_VALIDATION_FAILED")
