"""FizzStream Distributed Stream Processing events."""

from enterprise_fizzbuzz.domain.events._registry import EventType

EventType.register("STREAM_JOB_SUBMITTED")
EventType.register("STREAM_JOB_STARTED")
EventType.register("STREAM_JOB_FINISHED")
EventType.register("STREAM_JOB_FAILED")
EventType.register("STREAM_JOB_CANCELLED")
EventType.register("STREAM_JOB_RESTARTED")
EventType.register("STREAM_CHECKPOINT_STARTED")
EventType.register("STREAM_CHECKPOINT_COMPLETED")
EventType.register("STREAM_CHECKPOINT_FAILED")
EventType.register("STREAM_SAVEPOINT_CREATED")
EventType.register("STREAM_SAVEPOINT_RESTORED")
EventType.register("STREAM_WATERMARK_ADVANCED")
EventType.register("STREAM_WINDOW_FIRED")
EventType.register("STREAM_WINDOW_LATE_ELEMENT")
EventType.register("STREAM_OPERATOR_STARTED")
EventType.register("STREAM_OPERATOR_FAILED")
EventType.register("STREAM_BACKPRESSURE_DETECTED")
EventType.register("STREAM_BACKPRESSURE_CLEARED")
EventType.register("STREAM_SCALE_UP")
EventType.register("STREAM_SCALE_DOWN")
EventType.register("STREAM_CEP_PATTERN_MATCHED")
EventType.register("STREAM_CEP_PATTERN_TIMED_OUT")
EventType.register("STREAM_JOIN_COMPLETED")
EventType.register("STREAM_DASHBOARD_RENDERED")
EventType.register("STREAM_EVALUATION_EMITTED")
