"""FizzWeb HTTP server events."""

from enterprise_fizzbuzz.domain.events._registry import EventType

EventType.register("WEB_SERVER_STARTING")
EventType.register("WEB_SERVER_STARTED")
EventType.register("WEB_SERVER_DRAINING")
EventType.register("WEB_SERVER_STOPPED")
EventType.register("WEB_CONNECTION_ACCEPTED")
EventType.register("WEB_CONNECTION_CLOSED")
EventType.register("WEB_CONNECTION_IDLE")
EventType.register("WEB_CONNECTION_EVICTED")
EventType.register("WEB_TLS_HANDSHAKE_STARTED")
EventType.register("WEB_TLS_HANDSHAKE_COMPLETED")
EventType.register("WEB_TLS_HANDSHAKE_FAILED")
EventType.register("WEB_TLS_CERT_LOADED")
EventType.register("WEB_TLS_CERT_ROTATED")
EventType.register("WEB_TLS_CERT_EXPIRING")
EventType.register("WEB_REQUEST_RECEIVED")
EventType.register("WEB_REQUEST_ROUTED")
EventType.register("WEB_REQUEST_REJECTED")
EventType.register("WEB_RESPONSE_SENT")
EventType.register("WEB_RESPONSE_COMPRESSED")
EventType.register("WEB_VHOST_RESOLVED")
EventType.register("WEB_VHOST_MISMATCH")
EventType.register("WEB_STATIC_FILE_SERVED")
EventType.register("WEB_STATIC_304_NOT_MODIFIED")
EventType.register("WEB_STATIC_206_PARTIAL")
EventType.register("WEB_API_EVALUATE_SINGLE")
EventType.register("WEB_API_EVALUATE_RANGE")
EventType.register("WEB_API_HEALTH_CHECK")
EventType.register("WEB_API_METRICS")
EventType.register("WEB_WEBSOCKET_UPGRADE")
EventType.register("WEB_WEBSOCKET_MESSAGE")
EventType.register("WEB_WEBSOCKET_CLOSED")
EventType.register("WEB_WEBSOCKET_STREAM_STARTED")
EventType.register("WEB_HTTP2_STREAM_OPENED")
EventType.register("WEB_HTTP2_STREAM_CLOSED")
EventType.register("WEB_HTTP2_GOAWAY")
EventType.register("WEB_RATE_LIMITED")
EventType.register("WEB_CGI_EXECUTED")
EventType.register("WEB_CGI_TIMEOUT")
EventType.register("WEB_WSGI_INVOKED")
EventType.register("WEB_ACCESS_LOGGED")
EventType.register("WEB_ACCESS_LOG_ROTATED")
EventType.register("WEB_MIDDLEWARE_PROCESSED")
EventType.register("WEB_DASHBOARD_RENDERED")
EventType.register("WEB_EVALUATION_PROCESSED")
