"""FizzMVCC transaction engine events."""

from enterprise_fizzbuzz.domain.events._registry import EventType

EventType.register("MVCC_TXN_BEGUN")
EventType.register("MVCC_TXN_COMMITTED")
EventType.register("MVCC_TXN_ROLLED_BACK")
EventType.register("MVCC_TXN_ABORTED")
EventType.register("MVCC_SAVEPOINT_CREATED")
EventType.register("MVCC_SAVEPOINT_ROLLED_BACK")
EventType.register("MVCC_SAVEPOINT_RELEASED")
EventType.register("MVCC_WRITE_CONFLICT_DETECTED")
EventType.register("MVCC_SERIALIZATION_FAILURE")
EventType.register("MVCC_DEADLOCK_DETECTED")
EventType.register("MVCC_DEADLOCK_VICTIM_SELECTED")
EventType.register("MVCC_LOCK_ACQUIRED")
EventType.register("MVCC_LOCK_RELEASED")
EventType.register("MVCC_LOCK_TIMEOUT")
EventType.register("MVCC_LOCK_ESCALATED")
EventType.register("MVCC_GC_CYCLE_COMPLETED")
EventType.register("MVCC_GC_VERSIONS_RECLAIMED")
EventType.register("MVCC_GC_LONG_TXN_WARNING")
EventType.register("MVCC_GC_LONG_TXN_ABORTED")
EventType.register("MVCC_SNAPSHOT_CAPTURED")
EventType.register("MVCC_OCC_VALIDATION_FAILED")
EventType.register("MVCC_BTREE_SPLIT")
EventType.register("MVCC_BTREE_MERGE")
EventType.register("MVCC_PLAN_CACHED")
EventType.register("MVCC_PLAN_EVICTED")
EventType.register("MVCC_PLAN_INVALIDATED")
EventType.register("MVCC_CONN_CHECKED_OUT")
EventType.register("MVCC_CONN_CHECKED_IN")
EventType.register("MVCC_CONN_POOL_EXHAUSTED")
EventType.register("MVCC_CONN_VALIDATION_FAILED")
EventType.register("MVCC_ANALYZE_COMPLETED")
EventType.register("MVCC_AUTO_ANALYZE_TRIGGERED")
EventType.register("MVCC_EVALUATION_PROCESSED")
EventType.register("MVCC_DASHBOARD_RENDERED")
