"""FizzPolicy declarative policy engine events."""

from enterprise_fizzbuzz.domain.events._registry import EventType

EventType.register("POLICY_BUNDLE_BUILT")
EventType.register("POLICY_BUNDLE_SIGNED")
EventType.register("POLICY_BUNDLE_PUSHED")
EventType.register("POLICY_BUNDLE_ACTIVATED")
EventType.register("POLICY_BUNDLE_ROLLBACK")
EventType.register("POLICY_BUNDLE_REJECTED")
EventType.register("POLICY_BUNDLE_INTEGRITY_FAILED")
EventType.register("POLICY_EVALUATION_COMPLETED")
EventType.register("POLICY_EVALUATION_DENIED")
EventType.register("POLICY_EVALUATION_TIMEOUT")
EventType.register("POLICY_EVALUATION_ERROR")
EventType.register("POLICY_CACHE_HIT")
EventType.register("POLICY_CACHE_INVALIDATED")
EventType.register("POLICY_DATA_REFRESHED")
EventType.register("POLICY_DATA_STALE")
EventType.register("POLICY_DATA_ADAPTER_ERROR")
EventType.register("POLICY_TEST_SUITE_PASSED")
EventType.register("POLICY_TEST_SUITE_FAILED")
EventType.register("POLICY_COVERAGE_BELOW_THRESHOLD")
EventType.register("POLICY_HOT_RELOAD_STARTED")
EventType.register("POLICY_HOT_RELOAD_COMPLETED")
EventType.register("POLICY_HOT_RELOAD_FAILED")
EventType.register("POLICY_ADMISSION_DENIED")
EventType.register("POLICY_DECISION_LOGGED")
EventType.register("POLICY_DECISION_EXPORTED")
EventType.register("POLICY_MIDDLEWARE_PROCESSED")
