"""FizzAdmit admission controller and CRD operator events."""

from enterprise_fizzbuzz.domain.events._registry import EventType

EventType.register("FIZZADMIT_REQUEST_ADMITTED")
EventType.register("FIZZADMIT_REQUEST_DENIED")
EventType.register("FIZZADMIT_REQUEST_MUTATED")
EventType.register("FIZZADMIT_CHAIN_EXECUTED")
EventType.register("FIZZADMIT_QUOTA_EXCEEDED")
EventType.register("FIZZADMIT_QUOTA_UPDATED")
EventType.register("FIZZADMIT_LIMIT_DEFAULTED")
EventType.register("FIZZADMIT_LIMIT_VIOLATED")
EventType.register("FIZZADMIT_SECURITY_VIOLATION")
EventType.register("FIZZADMIT_IMAGE_DENIED")
EventType.register("FIZZADMIT_WEBHOOK_CALLED")
EventType.register("FIZZADMIT_WEBHOOK_FAILED")
EventType.register("FIZZADMIT_CRD_REGISTERED")
EventType.register("FIZZADMIT_CRD_DELETED")
EventType.register("FIZZADMIT_CRD_INSTANCE_CREATED")
EventType.register("FIZZADMIT_CRD_INSTANCE_UPDATED")
EventType.register("FIZZADMIT_CRD_INSTANCE_DELETED")
EventType.register("FIZZADMIT_OPERATOR_RECONCILE")
EventType.register("FIZZADMIT_OPERATOR_RECONCILE_ERROR")
EventType.register("FIZZADMIT_OPERATOR_LEADER_ELECTED")
EventType.register("FIZZADMIT_FINALIZER_ADDED")
EventType.register("FIZZADMIT_FINALIZER_REMOVED")
EventType.register("FIZZADMIT_FINALIZER_STUCK")
EventType.register("FIZZADMIT_GC_COLLECTED")
EventType.register("FIZZADMIT_CASCADE_DELETE")
EventType.register("FIZZADMIT_EVALUATION_PROCESSED")
EventType.register("FIZZADMIT_DASHBOARD_RENDERED")
